---
# tasks file for ansible-role-p10k

- name: Include OS specific variables.
  include_vars: "{{ ansible_system }}.yml"

- name: Install p10k
  include_tasks: "p10k-install.yml"

- name: Install p10k recommanded fonts
  include_tasks: "p10k-fonts.yml"
