---
- name: Create fonts directory
  file:
    path: "{{ fonts_path }}"
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Download powerlevel10k recommanded fonts
  get_url:
    url: "{{ item.url }}"
    dest: "{{ fonts_path }}/{{ item.name }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ p10k_font_urls }}"
